# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - publish

swift-build:
  stage: build
  tags:
    - swift
  before_script:
    - apt-get -q update
    - apt-get -q dist-upgrade -y
    - apt-get install -y libsqlite3-dev
    - swift package resolve
    - swift package update
  script:
    - swift build --build-tests
    - cp -r $(swift build --build-tests --show-bin-path)/VoteServerPackageTests.xctest package.xctest

  artifacts: 
    paths:
    - package.xctest
    expire_in: 1 hour

swift-unit-test:
  stage: test
  tags:
    - swift
  before_script:
    - apt-get -q update
    - apt-get -q dist-upgrade -y
    - apt-get install -y libsqlite3-dev
    - swift package resolve
    - swift package update
    - mkdir -p $(swift build --build-tests --show-bin-path)
    - cp -r package.xctest $(swift build --build-tests --show-bin-path)/VoteServerPackageTests.xctest
  script:
    - swift test --skip-build 

  needs: ["swift-build"]

 
build-docker-image:  
  stage: build
  tags:
    - dind
  script:
    - docker build -t $CI_REGISTRY/harcker/voteserver:$CI_COMMIT_REF_SLUG .
    - docker save --output voteserver.tar $CI_REGISTRY/harcker/voteserver:$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
    - voteserver.tar
    expire_in: 1 hour

publish-docker-image:  
  stage: publish
  tags:
    - dind
  script:
    - docker load --input voteserver.tar
    - docker push $CI_REGISTRY/harcker/voteserver:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  needs: ["build-docker-image", "swift-unit-test"]

bump-version:
  except:
   - branches
  variables:
    NEW_VERSION:
      value: ""
  tags:
    - dind
  script:
  - echo "Abc"
  - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@$REPO
  - git config --global user.email '${GITLAB_USER_EMAIL}'
  - git config --global user.name '${GITLAB_USER_ID}'
  - git add -A && git commit -m 'Bumped version (test)'
  - git tag $NEW_VERSION
  - git push origin HEAD:$BRANCH
  - git push origin $NEW_VERSION
  when: manual 