# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
unit-test-job:   # This job runs in the test stage.
  stage: test
  tags:
    - swift

  before_script:
    - apt-get -q update
    - apt-get -q dist-upgrade -y
    - apt-get install -y libsqlite3-dev
    - swift package resolve
    - swift package update
    
  script:
    - swift test

 
build-image:  
  stage: build
  tags:
    - dind
  script:
    - docker build -t $CI_REGISTRY/harcker/voteserver:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY/harcker/voteserver:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
